name: Build RMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - "**"

jobs:
  build:
    uses: grabpot/rmk/.github/workflows/user_build.yml@fix/splitserial
    with:
      keyboard_toml_path: "keyboard.toml"
      vial_json_path: "vial.json"
